name: Setup js-engine-run
description: Download, install, and setup js-engine-run to your path.
author: ahaoboy
branding:
  icon: play-circle
  color: white
inputs:
  test:
    description: "The test dir"
    required: true
  output:
    description: "the output test"
    required: false
  engines:
    description: "the engines"
    required: false
runs:
  using: "composite"
  steps:
    - uses: easy-install/js-engine-setup@v1
    - name: run
      shell: bash
      env:
        INPUT_TEST: ${{ inputs.test }}
        INPUT_OUTPUT: ${{ inputs.output }}
        INPUT_ENGINES: ${{ inputs.engines }}
      run: |
        # curl -L -o "info.json" "https://raw.githubusercontent.com/ahaoboy/js-engine-setup/main/info.json"

        path="${{ github.action_path }}"

        if [[ "$path" == *:* ]]; then
          path=$(echo "$path" | sed 's#\\#/#g' | sed 's#^\([A-Za-z]\):#/\L\1#')
        fi

        bun "$path/src/action.ts" > "${{ runner.os }}.json"